### ISSUE TITLE
hdf5 target fails to build with HDF5 1.8.4

### ISSUE THREAD

**Issue by kynan** [OP-DSL/OP2-Common#8]
``` bash
/usr/bin/mpiCC -g -fPIC -DUNIX -Wall -Iinclude -I/include  -c src/externlib/op_hdf5.c -L/lib -lhdf5 -lz  -o obj/externlib/op_hdf5.o 
src/externlib/op_hdf5.c: In function ‘op_set_core* op_decl_set_hdf5(const char*, const char*)’:
src/externlib/op_hdf5.c:64:49: error: too many arguments to function ‘hid_t H5Dopen1(hid_t, const char*)’
/usr/include/H5Dpublic.h:145:14: note: declared here
src/externlib/op_hdf5.c:59:17: warning: unused variable ‘dataspace’ [-Wunused-variable]
src/externlib/op_hdf5.c: In function ‘op_map_core* op_decl_map_hdf5(op_set, op_set, int, const char*, const char*)’:
src/externlib/op_hdf5.c:93:49: error: too many arguments to function ‘hid_t H5Dopen1(hid_t, const char*)’
/usr/include/H5Dpublic.h:145:14: note: declared here
src/externlib/op_hdf5.c:113:49: error: too many arguments to function ‘hid_t H5Dopen1(hid_t, const char*)’
/usr/include/H5Dpublic.h:145:14: note: declared here
src/externlib/op_hdf5.c:131:49: error: too many arguments to function ‘hid_t H5Dopen1(hid_t, const char*)’
/usr/include/H5Dpublic.h:145:14: note: declared here
src/externlib/op_hdf5.c:142:49: error: too many arguments to function ‘hid_t H5Dopen1(hid_t, const char*)’
/usr/include/H5Dpublic.h:145:14: note: declared here
src/externlib/op_hdf5.c: In function ‘op_dat_core* op_decl_dat_hdf5(op_set, int, const char*, const char*, const char*)’:
src/externlib/op_hdf5.c:192:49: error: too many arguments to function ‘hid_t H5Dopen1(hid_t, const char*)’
/usr/include/H5Dpublic.h:145:14: note: declared here
src/externlib/op_hdf5.c:203:49: error: too many arguments to function ‘hid_t H5Dopen1(hid_t, const char*)’
/usr/include/H5Dpublic.h:145:14: note: declared here
src/externlib/op_hdf5.c:221:49: error: too many arguments to function ‘hid_t H5Dopen1(hid_t, const char*)’
/usr/include/H5Dpublic.h:145:14: note: declared here
src/externlib/op_hdf5.c:237:49: error: too many arguments to function ‘hid_t H5Dopen1(hid_t, const char*)’
/usr/include/H5Dpublic.h:145:14: note: declared here
src/externlib/op_hdf5.c:247:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
src/externlib/op_hdf5.c:260:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
src/externlib/op_hdf5.c:273:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```
